#! /bin/sh -e

. /lib/lsb/init-functions

case "$1" in
  start)
    test -x /usr/bin/artvaluereport2-server || exit 0
    log_begin_msg "Starting artvaluereport2-development..."
    mkdir -p /srv/artvaluereport2-development
    'start-stop-daemon' '--start' '-b' '--quiet' '--make-pidfile' '-d' '/srv/artvaluereport2-development' '--exec' '/usr/bin/artvaluereport2-server' '--pidfile' '/var/run/artvaluereport2-development' '--' '--base-uri' 'http://seereason.com:9032/' '--http-port' '9032' '--top' '/srv/artvaluereport2-development' '--logs' '/var/log/artvaluereport2-development' '--log-mode' 'Production' '--static' '/usr/share/artvaluereport2-data' '--no-validate' '+RTS' '-IO' '-RTS'
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping artvaluereport2-development..."
    'start-stop-daemon' '--stop' '--quiet' '--retry' '60' '--oknodo' '--pidfile' '/var/run/artvaluereport2-development'
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: ${0} {start|stop}"
    exit 1
esac

exit 0
