#!/bin/sh

CONFIGDIR=$HOME/.autobuilder.d
CONFIGFILE=$CONFIGDIR/autobuilder.hs

[ "$USER" != "root" ] || {
    echo "You should not run this program as $USER.";
    exit 1
}
[ -d $CONFIGDIR ] || {
    echo "There is no configuration directory at $CONFIGDIR, an example of this directory can be obtained"
    echo "from http://seereason.com/autobuilder-config using this command:"
    echo "  darcs get http://seereason.com/autobuilder-config $CONFIGDIR"
    exit 1
}
[ -f $CONFIGFILE ] || {
    echo "No configuration file was found at $CONFIGFILE.  an example $CONFIGDIR directory can be obtained"
    echo "from http://seereason.com/autobuilder-config by removing $CONFIGDIR and using this command:"
    echo "  darcs get http://seereason.com/autobuilder-config $CONFIGDIR"
    exit 1
}
sudo HOME=${HOME} runhaskell -i$CONFIGDIR $CONFIGFILE $*
